---

- name: list all defined VMs
  virt:
    command: list_vms
  register: defined_vms

- name: stop VMs
  virt:
      name: "{{ item.name }}"
      state: shutdown
  with_items: "{{ l1_vms }}"
  when: item.name in defined_vms.list_vms

- name: undefine VMs
  virt:
      name: "{{ item.name }}"
      command: undefine
  with_items: "{{ l1_vms }}"
  when: item.name in defined_vms.list_vms

- name: stop pools
  command: "virsh pool-destroy {{ item.name }}"
  with_items: "{{ pools }}"
  ignore_errors: yes

- name: undefine pools
  command: "virsh pool-undefine {{ item.name }}"
  with_items: "{{ pools }}"
  ignore_errors: yes
