---

- copy:
    src: vsock_diag_test
    dest: /tmp/vsock_diag_test
    mode: 0777
    force: no

- name: Run vsock_diag_test ({{ vsock_diag_test_repeat | default(1) }} iterations)
  include_tasks: run_test.yml
  loop: "{{ range(1, (vsock_diag_test_repeat | default(1) | int) + 1) | list }}"
  loop_control:
    loop_var: vsock_diag_test_iteration
