---

- copy:
    src: iperf3
    dest: /tmp/iperf3
    mode: 0777
    force: no

- name: Start iperf3 server
  when: iperf_server is defined and iperf_server is not none
  vars:
    _server: "{{ iperf_server | default({}, true) }}"
  shell: "/tmp/iperf3 --vsock -s {{ _server.param | default('') }}"
  register: iperf_server_ret
  async: 200
  poll: 0

- name: Start iperf3 client
  when: iperf_client is defined and iperf_client is not none
  vars:
    _client: "{{ iperf_client | default({}, true) }}"
  shell: "/tmp/iperf3 --vsock -c {{ _client.cid }} {{ _client.param | default('') }}"
  register: iperf_client_ret

- name: Display iperf3 results
  when: iperf_client_ret.stdout_lines | default([]) | length > 0
  debug:
    var: iperf_client_ret.stdout_lines
