---

- copy:
    src: vsock_perf
    dest: /tmp/vsock_perf
    mode: 0777
    force: no

- name: Start vsock_perf server
  when: vsock_perf_server is defined and vsock_perf_server is not none
  vars:
    _server: "{{ vsock_perf_server | default({}, true) }}"
  shell: "/tmp/vsock_perf {{ _server.param | default('') }}"
  register: vsock_perf_server_ret
  async: 200
  poll: 0

- name: Start vsock_perf client
  when: vsock_perf_client is defined and vsock_perf_client is not none
  vars:
    _client: "{{ vsock_perf_client | default({}, true) }}"
  shell: "/tmp/vsock_perf --sender {{ _client.cid }} {{ _client.param | default('') }}"
  register: vsock_perf_client_ret

- name: Display vsock_perf_client results
  when: vsock_perf_client_ret.stdout_lines | default([]) | length > 0
  debug:
    var: vsock_perf_client_ret.stdout_lines
