---

- name: Start libvirtd service
  service:
    name: libvirtd
    state: started

- name: Disable SELinux
  selinux:
    policy: targeted
    state: permissive

- name: Setup nsswitch.conf for libvirt
  shell: 'grep libvirt /etc/nsswitch.conf || sed -i s/"files myhostname"/"files libvirt libvirt_guest myhostname"/g /etc/nsswitch.conf'

- name: define networks
  virt_net:
      name: "{{ item.name }}"
      command: define
      xml: "{{ lookup('template', 'net.xml.j2') }}"
  with_items: "{{ l0_nets }}"

- name: start networks
  virt_net:
      name: "{{ item.name }}"
      state: active
  with_items: "{{ l0_nets }}"

- template:
    src:  pool.xml.j2
    dest: "{{ item.xml }}"
  with_items: "{{ pools }}"

- name: create pool mount points
  file:
    path: "{{ item.local_dir }}"
    state: directory
  with_items: "{{ pools }}"

- name: define pools
  command: "virsh pool-define {{ item.xml }}"
  with_items: "{{ pools }}"

- name: start pools
  command: "virsh pool-start {{ item.name }}"
  with_items: "{{ pools }}"

- name: add VMs in the DHCP pool
  virt_net:
      name: "{{ item[0].name }}"
      command: modify
      xml: "<host mac='{{ item[1].mac }}' name='{{ item[1].name }}' ip='{{ item[1].ip }}'/>"
  with_nested:
    - "{{ l0_nets }}"
    - "{{ l0_vms }}"

- name: add nested VMs in the DHCP pool
  when: (l1_vms is defined) and (l1_vms != None)
  virt_net:
      name: "{{ item[0].name }}"
      command: modify
      xml: "<host mac='{{ item[1].mac }}' name='{{ item[1].name }}' ip='{{ item[1].ip }}'/>"
  with_nested:
    - "{{ l0_nets }}"
    - "{{ l1_vms }}"

- name: create VMs disk
  command: "qemu-img create -f qcow2 -F qcow2 -b {{ l0_disk_base }} {{ item.disk }}"
  with_items: "{{ l0_vms }}"

- name: define VMs
  virt:
      command: define
      xml: "{{ lookup('template', 'vm.xml.j2') }}"
  with_items: "{{ l0_vms }}"

- name: start VMs
  virt:
      name: "{{ item.name }}"
      state: running
  with_items: "{{ l0_vms }}"
