---

- name: install VMs tools
  package:
      name: "{{ item }}"
      state: present
  with_items:
    - '@virtualization'
    - libguestfs-tools
    - libvirt-nss
    - libvirt
    - python2-lxml
    - nfs-utils
