---
- hosts: localhost
  become: yes
  roles:
      - nfs_server_setup
      - vm_cleanup
      - vm_setup

- hosts: vsockvm0
  gather_facts: no
  become: yes
  pre_tasks:
      - name: Wait for vsockvm0 to become reachable
        wait_for_connection:

      - name: Gather facts for first time
        setup:

  roles:
      - vm_nested_setup

- hosts: vsockvm1
  gather_facts: no
  become: yes
  pre_tasks:
      - name: Wait for vsockvm1 to become reachable
        wait_for_connection:

      - name: Gather facts for first time
        setup:

- hosts: localhost
  tasks:
      - pause:
          prompt: "Enter to pass next phase"

- hosts: localhost
  become: yes
  roles:
      - vm_cleanup
      - nfs_server_cleanup
